edad=int(input("Ingrese edad: "))
print(type(edad))
edad=str(edad)
print(type(edad))

nombre=input("Ingrese el nombre: ")
apellido=input("Ingrese el apellido: ")
cedula=input("Ingrese la cedula: ")
print("Nombre:",nombre,"\nApellido:",apellido,"\nCedula:",cedula)
print(nombre*3)
print(len(nombre))
